# Generated by Django 2.2.4 on 2019-08-24 16:18

from django.db import migrations
#from shop.models import Category


def create_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')

    cat1 = Category.objects.create(category_name = 'Formals')
    cat1.save()
    cat2 = Category.objects.create(category_name = 'Sports')
    cat2.save()
    cat3 = Category.objects.create(category_name = 'Casuals')
    cat3.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
